@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjMwMTRmLWMzYjctNGZlZS05OTNhLWU1MDFmN2I2YjZjMyIsImVtYWlsIjoiYWxpZWZwZXJ0YW1hQGdtYWlsLmNvbSIsIm5hbWUiOiJhbGllZnBlcnRhbWFZWVkiLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTE3VDA2OjA5OjQwLjg1N1oiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTE3VDA2OjA5OjQwLjg1N1oiLCJyb2xlcyI6W10sImlhdCI6MTcxODYwNTI3MywiZXhwIjoxNzE4NjA3MDczfQ.nSu_gRwF2IwBSeLKVn_kGbntNOJDPsX9DgR8eCg_0XQ
### POST Try to login
POST http://localhost:8000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "aliefpertama@gmail.com",
    "password": "12345678"
}

### GET All Role
GET http://localhost:8000/role
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET Specific Role
GET http://localhost:8000/role/63249752-5cab-44fe-b276-6e3131965746
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### POST Create role 
POST http://localhost:8000/role
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name" : "Role test 1",
    "slug" : "Role-test-1",
    "permissions":[]
}

### PATCH Update role 
PATCH http://localhost:8000/role/f2ea7992-369f-4c04-9521-bc46f47251b7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name" : "Role test 1x",
    "slug" : "Role-test-1x",
    //"permissions":[
    //    {"id":"4ff2016b-c6b2-430b-a410-dcc449fa9743"}
    //]
    "permissions":[]
}

### Delete role 
DELETE http://localhost:8000/role/f2ea7992-369f-4c04-9521-bc46f47251b7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}